# Generated by Django 4.0.6 on 2022-12-05 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='unique_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.myuuidmodel'),
        ),
    ]
