# Generated by Django 4.0.6 on 2022-12-05 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_institution_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='institution',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='MyUUIDModel',
        ),
    ]
