# Generated by Django 4.0.6 on 2023-01-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_product_image_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(max_length=5000),
        ),
    ]
